### PR TITLE
Set y-max of the Load chart as 101 percent

### LINKED ISSUE #301: New 2.1 Overview Dashboard has some graphics issue, in the CPU-reactor graph
he missing lines are only on the overview dashboard, while in the per-server Dashboard it looks OK.

image

### PR DESCRIPTION
**Pull request by tzach**
fix #301

### CODE REVIEW

**Comment by tzach** [comment]
@amnonh please review

**Comment by amnonh** [comment]
We should probably define a type for graph with percentage and remove the duplication definitions of the y axis, it will be in a single place in types.jon

**Comment by tzach** [comment]
> We should probably define a type for a graph with percentage and remove the duplication definitions of the y axis, it will be in a single place in types.jon

No idea how to do that. Can you please send a new PR for such a fix?

**Comment by tzach** [comment]
@amnonh I'm merging since its a reported bu
Let's do the template definition in a follow-up PR

**Pull request merged**
