### PR TITLE
manager: Change Agent Memory graph to byte class

### PR DESCRIPTION
**Pull request by zimnx**
Memory is represented in bytes, not as integer.

### CODE REVIEW

**Comment by amnonh** [comment]
Did you do the changes in manager.master as well?
Also, please open an issue that this PR will close

**Comment by zimnx** [comment]
@amnonh thanks, wasn't aware of manager.master file. 
Added issue and aligned master template.

**Comment by amnonh** [comment]
you should also push the generated files:
run `./generate-dashboards.sh -M master` to generate the dashboard for master
and `./generate-dashboards.sh -M 2.1` to generate the dashboard for 2.1 and add the generated files.

**Comment by zimnx** [comment]
> you should also push the generated files:
> run `./generate-dashboards.sh -M master` to generate the dashboard for master
> and `./generate-dashboards.sh -M 2.1` to generate the dashboard for 2.1 and add the generated files.

done

**Pull request merged**
