### PR TITLE
Add start-grafana.sh script

### PR DESCRIPTION
**Pull request by duarten**
This patch extract the parts required to start a grafana container and
load the data source. This is useful for creating a grafana dashboard
to connect to running prometheus databases.

Signed-off-by: Duarte Nunes <duarte@scylladb.com>

### CODE REVIEW

**Comment by tzach** [comment]
I get an error when running with a version parameter

```
./start-all.sh -v 2017.1
a625e5b09bb37a113abe7c52aeb1e0502baae0fc00cd2a088df6eb1ef8365c54
Wait for Prometheus container to start..c6c40dbc4642a94d95e25f91b1a94c2f69a73afcdeadef7c73d24410672b2c3d
Wait for Grafana container to start../start-grafana.sh: line 70: [: 0: unary operator expected
../start-grafana.sh: line 70: [: 1: unary operator expected
```

**Comment by duarten** [comment]
Hum.. that line is exactly the same that was in ./start-all.sh. Does ./start-all.sh work for you before this patch?

[EDIT] Never mind, I see the issue. Will update :)

**Comment by duarten** [comment]
Should be fixed now.

**Comment by tzach** [comment]
I do not see the error message, but it looks the -v option is not respected.
On upstream ` ./start-all.sh -v 1.7` only load 1.7 dashboards, on this PR, it loads all the dashboards in `DEFAULT_VERSION`

BTW, I only see one commit in this PR from two days ago, how did you magically go back in time and change it?

**Comment by duarten** [comment]
On Aug 12, 2017 16:58, "Tzach Livyatan" <notifications@github.com> wrote:

I do not see the error message, but it looks the -v option is not respected.
On upstream ./start-all.sh -v 1.7 only load 1.7 dashboards, on this PR, it
loads all the dashboards in DEFAULT_VERSION


Ah, I'm calling. /start-grafana.sh with the wrong version, will fix.

BTW, I only see one commit in this PR from two days ago, how did you
magically go back in time and change it?


By doing a force push, the pull request is automatically updated.

**Comment by duarten** [comment]
Okay, everything should be fixed now (I hope).

**Pull request merged**
