### PR TITLE
add Thrift operation metrics

### PR DESCRIPTION
**Pull request by tzach**
This request adds Thrift to operation charts

### CODE REVIEW

**Comment by tzach** [comment]
@glommer please review

**Comment by tzach** [comment]
@tgrabiec ?

**Comment by tgrabiec** [comment]
Me and Glauber think that it would be better to sum the CQL and thrift requests on the "Request served per Server" and "Total requests served", etc, so that there is a single line per server. And maybe have separate graphs somewhere else for CQL and thrift servers, but that could come later.

**Comment by tzach** [comment]
Thanks @glommer @tgrabiec 
I will send a v2

**Pull request closed without merging**
