### PR TITLE
move prometheus targets from prometheus.yml to two new yml files

### PR DESCRIPTION
**Pull request by tzach**
The new targets files are easier to generate dynamically from external scripts

### CODE REVIEW

**Comment by tzach** [comment]
@glommer @amn please review

**Comment by glommer** [comment]
Tested and it works fine.

**Comment by amn** [comment]
@tzach I am not the contributor you were looking for.

**Comment by tzach** [comment]
@amn you can be if you want to :) sorry for calling you
@amnonh I was referring to you

**Pull request merged**
