### PR TITLE
Update cql_optimization.rst

### PR DESCRIPTION
**Pull request by lauranovich**
keep cross DC out of index by making sure it is not H1
does not need to be back ported

### CODE REVIEW

**Comment by tzach** [comment]
@lauranovich did we had a very similar PR earlier today?

**Comment by lauranovich** [comment]
this is on the 3.5 branch

**Comment by tzach** [comment]
You should not send PR to branches
Let the maintainer  backport

**Comment by lauranovich** [comment]
ok so I'll close  this one

**Comment by tzach** [comment]
Ping @amnonh  for backports

**Pull request closed without merging**
