### PR TITLE
Fix "Total Storage" pie chart - scylla-dash

### PR DESCRIPTION
**Pull request by roydahan**

### CODE REVIEW

**Comment by dorlaor** [comment]
Cheers! does it mean it will be accurate again?

**Comment by roydahan** [comment]
Yes!
screen shot 2017-06-06 at 18 49 59

**Comment by tzach** [comment]
Thanks @roydahan out of #181 #180 and #179, what should I look into?

**Comment by roydahan** [comment]
All of them.
Each patch fix one dashboard.
Sorry it's splitted into 3 PRs.

**Comment by tzach** [comment]
The pie looks much better, but it is higher than the two others charts in the same row
which is pretty ugly
image
I will try to solve this

**Comment by tzach** [comment]
@roydahan can you please try setting Legend Position as On Graph?
image

It keep the pie in the same highest
image

**Comment by roydahan** [comment]
sure, easy fix (I thought my looks better, but didn't look on overall alignment).

**Comment by tzach** [comment]
Thanks.
I have have a few free cycle, please send a new PR, if not, I will take care of it sometime in the near future

**Pull request merged**
