### PR TITLE
Remove a container and its volume

### LINKED ISSUE #155: kill-all.sh skript leaves volumes behind
after couple of management restarts disk may run out of space.

### PR DESCRIPTION
**Pull request by tzach**
Fix #155

### CODE REVIEW

**Comment by tzach** [comment]
@gleb-cloudius please test.
The question is, does the user ALWAYS wants to remove the volumes?
@glommer @amnonh thoughts ?

**Comment by glommer** [comment]
I think so. After the kill script is invoked the containers are gone, and the only way to get to them is through the filesystem. Without inspecting the container you can't even know where in the filesystem it is.

Add an option to leave the directories intact and if we really care, but default to delete

**Comment by gleb-cloudius** [comment]
On Sun, Apr 02, 2017 at 06:17:19AM -0700, Tzach Livyatan wrote:
> @gleb-cloudius please test.
We already tested it with Amnon.

--
			Gleb.

**Comment by tzach** [comment]
Thanks for the reviewers! So far its the smallest PR I sent or merged. Lets see who can do better.

**Pull request merged**
