### PR TITLE
Move to prometheus 2.3 v1

### PR DESCRIPTION
**Pull request by vladzcloudius**

### CODE REVIEW

**Comment by tzach** [comment]
@vladzcloudius what is the effect of upgrading on existing Prometheus data?

**Comment by slivne** [comment]
@amnonh
- can you please check this out - that the upgrade will also retain the data (I understand that vlad did some test - lets double check)
- can you please verify that the language has not changed and that all graphs and queries should work.

**Comment by amnonh** [comment]
I run into https://github.com/coreos/prometheus-operator/issues/830
Which mean there's a problem moving data from 1.8 to 2.x

The functions seem to work fine

**Comment by slivne** [comment]
The issue is closed on prometheus - so whats the solution/workaround ?

**Comment by vladzcloudius** [comment]
On 07/01/2018 01:27 AM, Tzach Livyatan wrote:
>
> @vladzcloudius <https://github.com/vladzcloudius> what is the effect 
> of upgrading on existing Prometheus data?
>

Data formats are not compatible between 1.x and 2.x.
There is a procedure of migrating the existing data from the old server 
to the new one: https://prometheus.io/docs/prometheus/2.0/migration/

**Comment by tzach** [comment]
Thanks @vladzcloudius 
We should document the upgrade process. A good timing to bump this project major release to make this breaking upgrade more visible

**Comment by tzach** [comment]
@vladzcloudius @amnonh can we close this PR?
I understand #344 is replacing this PR

**Comment by tzach** [comment]
> @vladzcloudius @amnonh can we close this PR?
> I understand #344 is replacing this PR
> 

@amnonh ?

**Pull request closed without merging**
