### PR TITLE
Fix cache total bytes and cache row granularity

### LINKED ISSUE #195: The "Cache Total Bytes" panel has incorrect query
It uses `scylla_cache_total{}`, and there is no such metric. It should use `scylla_cache_bytes_total{}`

### PR DESCRIPTION
**Pull request by tzach**
This PR solve conflict issue of @tgrabiec #197 #198 
Fixes #195

### CODE REVIEW

**Comment by tzach** [comment]
@tgrabiec my tests failed with Scylla docker nightly.
Could it be the new row chance metrics are not there yet?

**Comment by tgrabiec** [comment]
@tzach Do you have URL for the build or SHA1 of the commit it used? I don't know what "Scylla docker nightly" is. What do you mean by "tests failed" ?

**Comment by tzach** [comment]
test failed: metric used in this PR are not available from https://hub.docker.com/r/scylladb/scylla-nightly/

**Comment by tgrabiec** [comment]
@tzach I don't know which job pushes to that repo. Scylla master definitely has the new metrics.

**Comment by tzach** [comment]
AFAIK its part of the nightly build
@penberg probably knows best. Anyway, if you can validate this PR I will merge.

**Comment by tgrabiec** [comment]
@tzach I validated, looks ok.

**Comment by tzach** [comment]
Thanks @tgrabiec

**Pull request merged**
